# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  ...
}:

{
  powerManagement.cpuFreqGovernor="performance";

  boot.initrd.availableKernelModules = [
    "vmd"
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/root";
    fsType = "zfs";
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-id/nvme-Micron_2400_MTFDKBA512QFM_232441A9B7B9-part1";
    fsType = "vfat";
    options = [
      "umask=0077" # prevent /boot/loader/random-seed from being read
    ];
  };

  fileSystems."/nix" = {
    device = "rpool/nix";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "rpool/home";
    fsType = "zfs";
  };

  fileSystems."/var" = {
    device = "rpool/var";
    fsType = "zfs";
  };

  swapDevices = [
    {
      device = "/dev/disk/by-id/nvme-Micron_2400_MTFDKBA512QFM_232441A9B7B9-part6";
      priority = 1;
    }
  ];

  zramSwap = {
    enable = true;
    priority = 10;
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

# ZFS Config setup //todo improve to use disko maybe?

#sudo zpool create -O mountpoint=none -O atime=off -o ashift=12 -O acltype=posixacl -O xattr=sa -O compression=zstd -O dnodesize=auto -O normalization=formD rpool /dev/nvme0n1p7

#sudo zfs create -o mountpoint=legacy rpool/root
#sudo zfs create -o mountpoint=legacy rpool/nix
#sudo zfs create -o mountpoint=legacy rpool/home
#sudo zfs create -o mountpoint=legacy rpool/var

#reason for mountpoints is because by deafult zfs mounts the fs, but we want to explicitly mount the files with the NixOS intended way

